import el from '@/translations/el'
import { ExpoConfig } from 'expo/config'

const config: ExpoConfig = {
  name: 'Otobüsüm Anlık',
  slug: 'otobusum-anlik',
  version: '1.0.0',
  orientation: 'portrait',
  icon: './src/assets/icon.png',
  scheme: 'otobusum-anlik',
  userInterfaceStyle: 'automatic',
  newArchEnabled: false,
  extra: {
    eas: {
      projectId: '13cc0847-9f39-4aab-90d9-375e12df5087',
    },
  },
  ios: {
    supportsTablet: true,
    bundleIdentifier: 'com.otobusum.anlik',
    buildNumber: '1',
    icon: './src/assets/icon.png',
    requireFullScreen: false,
    userInterfaceStyle: 'automatic',
    infoPlist: {
      CFBundleDevelopmentRegion: 'en',
      CFBundleLocalizations: ['en', 'tr', 'ar', 'de', 'fr', 'ru', 'uk', 'az', 'it', 'el', 'ja', 'ko', 'es', 'cs', 'da', 'nl', 'fi', 'hi', 'zh-Hans', 'hu', 'nb', 'pl', 'pt', 'sk', 'sv', 'hr', 'zh-Hant', 'ca', 'ms', 'id', 'vi', 'th', 'zh-HK', 'ro', 'tk', 'ug', 'ur', 'uz', 'sr', 'mn', 'lb', 'lt', 'ky', 'kk', 'ka', 'et', 'bg', 'bs', 'sq', 'tt', 'bo', 'lv', 'lo', 'mk', 'fa', 'ga', 'is'],
      CFBundleAllowMixedLocalizations: true,
      LSApplicationQueriesSchemes: ['maps', 'http', 'https'],
      ITSAppUsesNonExemptEncryption: false,
      UILaunchStoryboardName: 'SplashScreen',
      UIRequiredDeviceCapabilities: ['arm64'],
      UISupportedInterfaceOrientations: ['UIInterfaceOrientationPortrait'],
      UISupportedInterfaceOrientations_iPad: [
        'UIInterfaceOrientationPortrait',
        'UIInterfaceOrientationPortraitUpsideDown',
        'UIInterfaceOrientationLandscapeLeft',
        'UIInterfaceOrientationLandscapeRight'
      ],
      UIViewControllerBasedStatusBarAppearance: false,
      UIStatusBarStyle: 'UIStatusBarStyleDefault'
    },
    associatedDomains: ['applinks:otobusum-anlik.app'],
    splash: {
      image: './src/assets/splash.png',
      backgroundColor: '#d8d8d8',
      resizeMode: 'contain',
      hideOnLaunch: false
    },
    usesAppleSignIn: false
  },
  updates: {
    url: 'https://u.expo.dev/13cc0847-9f39-4aab-90d9-375e12df5087',
    requestHeaders: {
      'expo-channel-name': 'production',
    },
  },
  runtimeVersion: {
    policy: 'appVersion',
  },
  plugins: [
    'expo-dev-client',
    'expo-router',
    'expo-localization',
    'expo-location',
    [
      'expo-splash-screen',
      {
        image: './src/assets/splash.png',
        backgroundColor: '#d8d8d8',
        resizeMode: 'contain'
      },
    ],
  ],
  locales: {
    en: './src/translations/expo/en.json',
    tr: './src/translations/expo/tr.json',
    ar: './src/translations/expo/ar.json',
    de: './src/translations/expo/de.json',
    fr: './src/translations/expo/fr.json',
    ru: './src/translations/expo/ru.json',
    uk: './src/translations/expo/uk.json',
    az: './src/translations/expo/az.json',
    it: './src/translations/expo/it.json',
    el: './src/translations/expo/el.json',
    ja: './src/translations/expo/ja.json',
    ko: './src/translations/expo/ko.json',
    es: './src/translations/expo/es.json',
    cs: './src/translations/expo/cs.json',
    da: './src/translations/expo/da.json',
    nl: './src/translations/expo/nl.json',
    fi: './src/translations/expo/fi.json',
    hi: './src/translations/expo/hi.json',
    'zh-Hans': './src/translations/expo/zh-Hans.json',
    hu: './src/translations/expo/hu.json',
    nb: './src/translations/expo/nb.json',
    pl: './src/translations/expo/pl.json',
    pt: './src/translations/expo/pt.json',
    sk: './src/translations/expo/sk.json',
    sv: './src/translations/expo/sv.json',
    hr: './src/translations/expo/hr.json',
    'zh-Hant': './src/translations/expo/zh-Hant.json',
    ca: './src/translations/expo/ca.json',
    ms: './src/translations/expo/ms.json',
    id: './src/translations/expo/id.json',
    vi: './src/translations/expo/vi.json',
    th: './src/translations/expo/th.json',
    'zh-HK': './src/translations/expo/zh-HK.json',
    ro: './src/translations/expo/ro.json',
    tk: './src/translations/expo/tk.json',
    ug: './src/translations/expo/ug.json',
    ur: './src/translations/expo/ur.json',
    uz: './src/translations/expo/uz.json',
    sr: './src/translations/expo/sr.json',
    mn: './src/translations/expo/mn.json',
    lb: './src/translations/expo/lb.json',
    lt: './src/translations/expo/lt.json',
    ky: './src/translations/expo/ky.json',
    kk: './src/translations/expo/kk.json',
    ka: './src/translations/expo/ka.json',
    et: './src/translations/expo/et.json',
    bg: './src/translations/expo/bg.json',
    bs: './src/translations/expo/bs.json',
    sq: './src/translations/expo/sq.json',
    tt: './src/translations/expo/tt.json',
    bo: './src/translations/expo/bo.json',
    lv: './src/translations/expo/lv.json',
    lo: './src/translations/expo/lo.json',
    mk: './src/translations/expo/mk.json',
    fa: './src/translations/expo/fa.json',
    ga: './src/translations/expo/ga.json',
    is: './src/translations/expo/is.json',
  },
  experiments: {
    typedRoutes: true,
  },
}

export default config
